name: Deploy Azure Function App to Azure

on:
  push:
    branches:
      - master  # of 'main' als dat je hoofdbranch is

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Publish to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'cippgyo6o'
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
